spring:
  application:
    name: mxdwn-api
  datasource:
    url: jdbc:postgresql://localhost:5438/mxdwn
    username: mxdwn_dev
    password: mxdwnpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
